services:
  common-kafka:
#    image: bitnami/kafka:3.3.1
# 20231220 2023.5 NXP-32157
    image: bitnami/kafka:3.6.0
    deploy:
      resources: 
        limits: 
          memory: 2GB
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      
      - KAFKA_ENABLE_KRAFT=yes
      # cat /proc/sys/kernel/random/uuid | tr -d '-' | base64 | cut -b 1-22
      #- KAFKA_KRAFT_CLUSTER_ID=MDZkOGQ2YTY3ZmJlNGNjYj
      - KAFKA_CFG_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
      - BITNAMI_DEBUG=yes
      - TZ=US/Pacific
    volumes:
      - vol-kafka-data:/bitnami/kafka:rw
    ports:
      - "9092:9092"
      - "9094:9094"
#    deploy:
#      resources: 
#        limits: 
#          memory: 4GB

